
add_library(Qt5::QGeoServiceProviderFactoryMapboxGL MODULE IMPORTED)

_populate_Location_plugin_properties(QGeoServiceProviderFactoryMapboxGL RELEASE "geoservices/qtgeoservices_mapboxgl.dll")
_populate_Location_plugin_properties(QGeoServiceProviderFactoryMapboxGL DEBUG "geoservices/qtgeoservices_mapboxgld.dll")

list(APPEND Qt5Location_PLUGINS Qt5::QGeoServiceProviderFactoryMapboxGL)
